apiVersion: apps/v1
kind: Deployment
metadata:
  name: sts-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sts-app
  template:
    metadata:
      labels:
        app: sts-app
    spec:
      containers:
        - name: sts-container
          image: ldclakmal/ballerina-sts:latest
          ports:
            - containerPort: 9444
---
apiVersion: v1
kind: Service
metadata:
  name: sts-svc
spec:
  selector:
    app: sts-app
  ports:
    - protocol: TCP
      port: 9444
      targetPort: 9444
  type: ClusterIP
