[container.image]
name="sentiment-api"
tag="1.0.0"
repository="anuruddhal"

[cloud.deployment]
internal_domain_name="sentiment-api-svc"

[[cloud.config.files]]
file="Config.toml"
name="sentiment-api-config"

[[container.copy.files]]
sourceFile="resources"
target="resources"