name: Push Docker Images to Docker Hub

on:
    push:
      branches:
        - master
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: anuruddhal
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Build and Push DB Image
        uses: docker/build-push-action@v4
        with:
          context: ./back-end/db-setup
          file: ./back-end/db-setup/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: anuruddhal/mysql-forum-db:latest,anuruddhal/mysql-forum-db:1.0.0
      - name: Build and Push Front End Image
        uses: docker/build-push-action@v4
        with:
            context: ./front-end
            file: ./front-end/Dockerfile
            platforms: linux/amd64,linux/arm64
            push: true
            tags: anuruddhal/forum:latest,anuruddhal/forum:1.0.0   
